timeout: 780s
steps:
  - id: build and push app image
    name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - --destination=asia.gcr.io/$PROJECT_ID/laravel_test_app:${SHORT_SHA}
      - --cache=true
      - --cache-ttl=6h
      - --dockerfile=./infra/docker/php/Dockerfile_prod
      - --build-arg=PROJECT_ID=${PROJECT_ID}

  - id: build and push web image
    name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - --destination=asia.gcr.io/$PROJECT_ID/laravel_test_web:${SHORT_SHA}
      - --cache=true
      - --cache-ttl=6h
      - --dockerfile=./infra/docker/nginx/Dockerfile_prod
      - --build-arg=PROJECT_ID=${PROJECT_ID}
      
  - id: access the id_github file from secret manager
    name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud secrets versions access latest --secret=github-secret > /root/.ssh/id_github
    volumes:
      - name: 'ssh'
        path: /root/.ssh
        
  - id: set up git with key and domain
    name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        chmod 600 /root/.ssh/id_github
        cat <<EOF >/root/.ssh/config
        Hostname github.com
        IdentityFile /root/.ssh/id_github
        EOF
        ssh-keyscan -t rsa github.com > /root/.ssh/known_hosts
    volumes:
      - name: 'ssh'
        path: /root/.ssh

  - id: connect to the repository
    name: 'gcr.io/cloud-builders/git'
    args:
      - clone
      - --recurse-submodules
      - git@github.com:cinra/manifests-newmedia.git
    volumes:
      - name: 'ssh'
        path: /root/.ssh
        
  - id: switch to candidate-dev branch
    name: 'gcr.io/cloud-builders/gcloud'
    dir: go-grpc-health-probe-sample-manifests
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        set -x && \
        git config --global user.email $(git log --format='%an <%ae>' -n 1 HEAD | sed 's/.*\<\([^>]*\)\>.*/\1/g') && \
        git fetch origin candidate-dev && git switch candidate-dev && \
        git fetch origin master && git merge origin/master
    volumes:
      - name: 'ssh'
        path: /root/.ssh
        
  - id: generate manifest for laravel-test
    name: 'gcr.io/cloud-builders/gcloud'
    dir: laravel-test
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        set -x && \
        sed "s/COMMIT_SHA/${SHORT_SHA}/g" > deployment.yml

  - id: push generated manifests to candidate-dev branch
    name: 'gcr.io/cloud-builders/gcloud'
    dir: go-grpc-health-probe-sample-manifests
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        set -x && \
        git add laravel-test/deployment.yml && \
        git commit \
        --author="Cloud Build Service Account <$(gcloud auth list --filter=status:ACTIVE --format='value(account)')>" \
        -m "Deploying images
        - asia.gcr.io/dev-xdu/laravel_test_app:${SHORT_SHA}
        - asia.gcr.io/dev-xdu/laravel_test_web:${SHORT_SHA}
        Built from commit ${COMMIT_SHA} of repository manifests-newmedia" && \
        git push origin candidate-dev
    volumes:
      - name: 'ssh'
        path: /root/.ssh

# Manifestã®PR
  - id: Create PR to main
    name: 'gcr.io/cloud-builders/curl'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      gcloud secrets versions access latest --secret=github-token >  /root/.ssh/github_access_token \
      _ACCESS_TOKEN=`cat /root/.ssh/github_access_token`
      #repo=`echo -n cinra/manifests-newmedia | sed "s/.git//"`
      json=$(cat << EOS
      {"title": "good title", "head": "candidate-dev", "base": "main", "body": "great PR messages"}
      EOS
      )
      curl -H 'Content-Type:application/json' \
          -H "Authorization: token ${_ACCESS_TOKEN}" \
          "https://api.github.com/repos/cinra/manifests-newmedia/pulls" \
          -d "$json"
    volumes:
    - name: 'ssh'
      path: /root/.ssh
